// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZzGMyYCx-8vdbwVh_caBSqKNSf85szmk',
    appId: '1:985872097815:web:90fab53d22ff60f068b252',
    messagingSenderId: '985872097815',
    projectId: 'hmw-resort',
    authDomain: 'hmw-resort.firebaseapp.com',
    storageBucket: 'hmw-resort.firebasestorage.app',
    measurementId: 'G-M9R1Z1N0FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASH_ANnyZV3WxnW9x4AqWRS-lL5mK8xSU',
    appId: '1:985872097815:android:105460a7b409fb6c68b252',
    messagingSenderId: '985872097815',
    projectId: 'hmw-resort',
    storageBucket: 'hmw-resort.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpTyu0zet0RFrqMu8Oz0t7wAWD4FC9tjY',
    appId: '1:985872097815:ios:45c62b1168d99acd68b252',
    messagingSenderId: '985872097815',
    projectId: 'hmw-resort',
    storageBucket: 'hmw-resort.firebasestorage.app',
    iosClientId: '985872097815-n6ckqh6rbmkjo7emc3agoa5nrqdh2m52.apps.googleusercontent.com',
    iosBundleId: 'com.example.hemawanResort',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpTyu0zet0RFrqMu8Oz0t7wAWD4FC9tjY',
    appId: '1:985872097815:ios:45c62b1168d99acd68b252',
    messagingSenderId: '985872097815',
    projectId: 'hmw-resort',
    storageBucket: 'hmw-resort.firebasestorage.app',
    iosClientId: '985872097815-n6ckqh6rbmkjo7emc3agoa5nrqdh2m52.apps.googleusercontent.com',
    iosBundleId: 'com.example.hemawanResort',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZzGMyYCx-8vdbwVh_caBSqKNSf85szmk',
    appId: '1:985872097815:web:ffd025ef56a62ae168b252',
    messagingSenderId: '985872097815',
    projectId: 'hmw-resort',
    authDomain: 'hmw-resort.firebaseapp.com',
    storageBucket: 'hmw-resort.firebasestorage.app',
    measurementId: 'G-NPRFRGYWFK',
  );
}
